config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'static_pages#index'
  get 'static_pages/index'

  resources :users
  resources :characters do
    resources :for_attributes
  end

end

app/models/character.rb
class Character < ActiveRecord::Base
  belongs_to :user
  has_many :for_attributes, dependent: :destroy
  mount_uploader :image, ImageUploader
  validates :char_name, presence: true
  validates :image, presence: true
  validate :image_size

  private
    
      # Validates the size of an uploaded picture.
    def image_size
      if image.size > 5.megabytes
        errors.add(:image, "should be less than 5MB")
      end
    end

  
end

app/models/for_attribute.rb
class ForAttribute < ActiveRecord::Base
  belongs_to :character
  mount_uploader :image, ImageUploader
  validates :name, presence: true
  validates :image, presence: true
  validate :image_size

  private

      # Validates the size of an uploaded picture.
    def image_size
      if image.size > 5.megabytes
        errors.add(:image, "should be less than 5MB")
      end
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :characters, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable

  def login=(login)
    @login = login
  end

  def login
    @login || self.username || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
      conditions = warden_conditions.dup
      if login = conditions.delete(:login)
        where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
      elsif conditions.has_key?(:username) || conditions.has_key?(:email)
        where(conditions.to_h).first
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

protected
def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
   devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
   devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_character, only: [:show, :edit, :update, :destroy]
  before_filter :require_permission, only: [:destroy, :edit, :update]
  before_action :all_characters, only: [:index, :create,  :destroy]
  respond_to :html, :js

  def index
    #@user = current_user
    #@characters = current_user.characters.order("created_at DESC").page(params[:page]).per(5)
  end

  def show
    #@user = current_user
    @for_attributes = @character.for_attributes.order("created_at DESC")
    respond_with(@character)
  end

  def new
    @character = current_user.characters.build
  end

  def edit

  end

  def create
    #@user = current_user
    @character = current_user.characters.build(character_params)
    #@characters = current_user.characters.order("created_at DESC").page(params[:page]).per(5)
    respond_to do |format|
      if @character.save
        format.js
      else
        format.html { redirect_to characters_path }
        format.js
      end
    end
  end

  def update
    @character.update(character_params)
    respond_to do |format|
      if @character.save
        format.js
      else
        format.html { redirect_to characters_path }
      end
    end
  end

  def destroy
    @character.destroy

    respond_to do |format|
      format.js
    end
  end

  private

  def all_characters
    @characters = current_user.characters.order("created_at DESC").page(params[:page]).per(5)
  end

  def set_character
    @character = current_user.characters.find(params[:id])
  end

  def character_params
    params.require(:character).permit(:char_name, :image)
  end

  def require_permission
    set_character
    unless current_user == @character.user
      redirect_to(root_path,:notice=>"You can edit/delete only characters you created")
    end
  end

end

app/controllers/for_attributes_controller.rb
class ForAttributesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_for_attribute, only: [:show, :edit, :update, :destroy]
  before_action :set_character, only: [:index, :show, :new, :edit, :create, :update, :destroy]
  before_action :require_permission, only: [:destroy, :edit, :update]
  respond_to :html, :js

  def index
    #@character = Character.find(params[:character_id])
    @for_attributes = @character.for_attributes.order("created_at DESC").page(params[:page]).per(5)

  end

  def show
    #@character = Character.find(params[:character_id])
    respond_with(@for_attribute)
  end

  def new
    #@character = Character.find(params[:character_id])
    @for_attribute = ForAttribute.new
  end

  def edit
    #@character = Character.find(params[:character_id])
    @for_attribute = @character.for_attributes.find(params[:id])

  end

  def create
    #@character = Character.find(params[:character_id])
    @for_attribute = @character.for_attributes.build(for_attribute_params)
    respond_to do |format|
      if @for_attribute.save
        format.html { redirect_to character_path(@character) }
        format.js
      else
        format.html { redirect_to character_path(@character) }
      end
    end
  end

  def update
    #@character = Character.find(params[:character_id])
    @for_attribute.update(for_attribute_params)
    respond_to do |format|
      if @for_attribute.save
        format.html { redirect_to character_path(@character) }
        format.js
      else
        format.html { redirect_to character_path(@character) }
      end
    end
  end

  def destroy
    @for_attribute.destroy

    respond_to do |format|
      format.html {  redirect_to character_path(@character)  }
      format.js
      flash[:success] = "Character deleted!"
    end
  end

  private

  def set_character
    @character = current_user.characters.find(params[:character_id])
  end

  def set_for_attribute
    @for_attribute = ForAttribute.find(params[:id])
  end

  def for_attribute_params
    params.require(:for_attribute).permit(:name, :value, :image)
  end

  def require_permission
      unless current_user == @character.user
        redirect_to(root_path,:notice=>"You can only edit/delete attributes of the characters you created")
      end
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    render ('static_pages/index')
  end

  def show
   @user = current_user
   @characters = @user.characters
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title = '')
    base_title = "Edit App"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/for_attributes_helper.rb
module ForAttributesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/characters/_character.html.erb
<td><%= image_tag character.image.url(:thumb) if character.image? %></td>
<td><strong><%= link_to character.char_name, character_path(character) %></strong></td>
<td><%= link_to 'Delete', character_path(character) , data: {confirm: "Are You Sure?"}, method: :delete, remote: true,  class: 'btn btn-danger' %>
</td>
<td><%= link_to 'Edit', edit_character_path(character), role: 'button', id: 'edit_char', class: 'btn btn-info', remote: true %></td>

app/views/characters/_for_attribute.html.erb
<td><%= image_tag for_attribute.image.url(:thumb) if for_attribute.image? %></td>
<td><strong><%= for_attribute.value %></strong></td>
<td><strong><%= for_attribute.name %></strong></td>
<td><%= link_to 'Delete', character_for_attribute_path(@character, for_attribute) , data: {confirm: "Are You Sure?"}, method: :delete,  class: 'btn btn-danger', remote: true %>
</td>
<td><%= link_to 'Edit', edit_character_for_attribute_path(@character, for_attribute) , role: 'button', class: 'btn', remote: true %></td>

app/views/characters/_form.html.erb
<%= form_for(@character, html: {  multipart: true  }) do |f| %>
<% if @character.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@character.errors.count, "error") %> prohibited this character from being saved:</h2>

  <ul>
    <% @character.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= f.label :char_name, 'Character Name', class: "form-group" %><br>
  <%= f.text_field :char_name, class: "form-control" %>
</div>

<%= f.file_field :image %>

<div class="actions">
  <%= f.submit class: "btn btn-block btn-warning" %>
</div>
<% end %>

app/views/characters/_form_new.html.erb
<%= form_for(@character, remote: true, html: {  multipart: true  }) do |f| %>
<% if @character.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@character.errors.count, "error") %> prohibited this character from being saved:</h2>

  <ul>
    <% @character.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= f.label :char_name, 'Character Name' %><br>
  <%= f.text_field :char_name %>
</div>

<%= f.file_field :image %>
<div class="actions">
  <%= f.submit class: "btn btn-warning" %>
</div>

<%= hidden_field_tag 'authenticity_token', form_authenticity_token %>

<% end %>

app/views/characters/_form_new_attr.html.erb
<%= form_for([@character, @for_attribute], html: {  multipart: true, remote: true  }, remote: false ) do |f| %>
<div class="field">
  <%= f.label :name, 'Attribute Name' %><br>
  <%= f.text_field :name %>
</div>
<div class="field">
  <%= f.label :value %><br>
  <%= f.number_field :value %>
</div>
<div class="field">
  <%= f.file_field :image %>
</div>
<div class="actions">
  <%= f.submit class: "btn btn-warning" %>
</div>
<% end %>

app/views/characters/create.js.erb
<% if @character.errors.any? %>
$(".ajax-form").html("<%= escape_javascript (render ("form_new")) %>");
<% else	%>
$('table').html("<%= escape_javascript (render ("table")) %>");
$('#new_character').remove();
$('#new_link').show();
<% end %>

app/views/characters/destroy.js.erb
$('#<%= @character.id %>').remove();

app/views/characters/edit.html.erb
<h1>Update Your Character</h1>
<div class="form-group">
	<%= render 'form' %>

	<%= link_to 'Show', @character %> |
	<%= link_to 'Back', current_user %>
</div>

app/views/characters/edit.js.erb
$('#new_character').remove();
$('#edit_character_<%= @character.id %>').remove();
$('#new_link').hide().after('<%= escape_javascript(render ("form_new")) %>');

app/views/characters/index.html.erb
<h1>Your Characters</h1>
<div class="ajax-form clearfix">
  <%= link_to 'New Character', new_character_path, id: 'new_link', class: 'btn btn-warning', remote: true %>
</div>
<div class="table-block clearfix">
  <%= paginate @characters %>
  <table class="table">
    <%= render partial: "table" %>
  </table>
  <%= link_to 'Back', static_pages_index_path %>
</div>

app/views/characters/new.html.erb
<h1>New Character</h1>
<div class="form-group">
	<%= render 'form' %>

	<%= link_to 'Back', characters_path %>
</div>

app/views/characters/new.js.erb
$('#new_link').hide().after('<%= escape_javascript(render ("form_new")) %>');

app/views/characters/show.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag @character.image.url(:thumb_lg), class: "center-block" %>
<h1><%= @character.char_name %></h1>
<div class="ajax-form-atr clearfix">
	<%= link_to 'New Character Attributes', new_character_for_attribute_path(@character) , role: 'button', id: "new_atr_link", class: 'btn btn-warning move_link', remote: true %>
</div>
<div class="table-block clearfix">


	<table class="table">
		<tr>
			<th class="col-sm-2">Avatar</th>
			<th class="col-sm-2">Value</th>
			<th class="col-sm-4">Name</th>
			<th class="col-sm-2">Delete Attribute</th>
			<th class="col-sm-2">Update Attribute</th>
		</tr>
		<% @for_attributes.each do |for_attribute| %>
		<tr id="<%= for_attribute.id %>">
			<%= render for_attribute %>
		</tr>
		<% end %>
	</table>

	<div class="move_link">
		<%= link_to 'Back', characters_path %>
	</div>
</div>

app/views/characters/update.js.erb
$('#edit_character_<%= @character.id %>').remove();
$('#new_link').show();
$('#<%= @character.id %>').html("<%= escape_javascript(render(@character)) %>");

app/views/for_attributes/_for_attribute.html.erb
<td><%= image_tag for_attribute.image.url(:thumb) if for_attribute.image? %></td>
<td><strong><%= for_attribute.value %></strong></td>
<td><strong><%= for_attribute.name %></strong></td>
<td><%= link_to 'Delete', character_for_attribute_path(@character, for_attribute) , data: {confirm: "Are You Sure?"}, method: :delete,  class: 'btn btn-danger', remote: true %>
</td>
<td><%= link_to 'Edit', edit_character_for_attribute_path(@character, for_attribute) , role: 'button', class: 'btn btn-info', remote: true %></td>

app/views/for_attributes/_form.html.erb
<%= form_for [@user, @character, @for_attribute] do |f| %>
<% if @for_attribute.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@for_attribute.errors.count, "error") %> prohibited this for_attribute from being saved:</h2>

  <ul>
    <% @for_attribute.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= f.label :name, class: "form-group" %><br>
  <%= f.text_field :name, class: "form-control" %>
</div>
<div class="field">
  <%= f.label :value, class: "form-group" %><br>
  <%= f.number_field :value, class: "form-control" %>
</div>

<%= f.file_field :image %>

<div class="actions">
  <%= f.submit class: "btn btn-block btn-warning" %>
</div>
<% end %>

app/views/for_attributes/_form_new.html.erb
<%= form_for([@user,@character, @for_attribute], html: {  multipart: true, remote: true  }, remote: true ) do |f| %>
<div class="field">
  <%= f.label :name, 'Character Name' %><br>
  <%= f.text_field :name %>
</div>
<div class="field">
  <%= f.label :value %><br>
  <%= f.number_field :value %>
</div>
<div class="field">
  <%= f.file_field :image %>
</div>
<div class="actions">
  <%= f.submit class: "btn btn-warning" %>
</div>
<% end %>

app/views/for_attributes/create.js.erb
$('#new_for_attribute').remove();
$('#new_atr_link').show();
$('#<%= @for_attribute.id %>').append("<%= escape_javascript(render(@for_attribute)) %>");

app/views/for_attributes/destroy.js.erb
$('#<%= @for_attribute.id %>').remove();

app/views/for_attributes/edit.html.erb
<h1>Editing For Attribute</h1>
<div class="form-group">
	<%= render 'form' %>

	<%= link_to 'Show', '#' %> |
	<%= link_to 'Back', '#' %>
</div>

app/views/for_attributes/edit.js.erb
$('#new_for_attribute').remove();
$('#edit_for_attribute_<%= @for_attribute.id %>').remove();
$('#new_atr_link').hide().after('<%= escape_javascript(render ("characters/form_new_attr")) %>');

app/views/for_attributes/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @character.char_name %></h1>
<div class="ajax-form-atr clearfix">
  <%= link_to 'New Attribute', new_user_character_for_attribute_path(@user,@character), id: 'new_atr_link', class: 'btn btn-warning', remote: true %>
</div>

<div class="table-block clearfix">
  <%= paginate @for_attributes %>
  <table class="table">
    <thead>
      <tr>
        <th class="col-sm-2">Avatar</th>
        <th class="col-sm-4">Name</th>
        <th class="col-sm-2">Value</th>
        <th class="col-sm-2">Delete Attribute</th>
        <th class="col-sm-2">Update Attribute</th>
      </tr>
      <% @for_attributes.each do |for_attribute| %>
      <tr id="<%= for_attribute.id %>">
        <%= render for_attribute %>
      </tr>
      <% end %>
    </thead>
  </table>
  <%= link_to 'Back', user_characters_path %>
</div>

app/views/for_attributes/new.html.erb
<h1>New Character Attribute</h1>
<div class="form-group">
	<%= render 'form' %>

	<%= link_to 'Back', characters_path %>
</div>

app/views/for_attributes/new.js.erb
$('#new_atr_link').hide().after('<%= escape_javascript(render ("characters/form_new_attr")) %>');

app/views/for_attributes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @for_attribute.name %>
</p>

<p>
  <strong>Value:</strong>
  <%= @for_attribute.value %>
</p>

<p>
  <strong>Image:</strong>
  <%= @for_attribute.image %>
</p>

<p>
  <strong>Character:</strong>
  <%= @for_attribute.character %>
</p>

<%= link_to 'Edit', edit_for_attribute_path(@for_attribute) %> |
<%= link_to 'Back', for_attributes_path %>

app/views/for_attributes/update.js.erb
$('#edit_for_attribute_<%= @for_attribute.id %>').remove();
$('#new_atr_link').show();
$('#<%= @for_attribute.id %>').html("<%= escape_javascript(render(@for_attribute)) %>");

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.edit.org/">Edit app</a>
    by <a href="http://www.edit.com/">Aleksandar Golubovic</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.edit.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
		<%= link_to "Edit App", '#', id: "logo" %>
		<nav>
			<ul class="nav navbar-nav navbar-right">
				<% if user_signed_in? %>
				<li><%= link_to "Home", static_pages_index_path %></li>
				<li><%= link_to "Update Profile", edit_user_registration_path %></li>
				<li><%= link_to "Characters", characters_path %></li>
				<li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
				<% else %>
				<li><%= link_to "Log in", new_user_session_path %></li>
				<% end %>
			</ul>
		</nav>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag  'application', media: 'all',
  'data-turbolinks-track' => true %>
  <%= javascript_include_tag :defaults,  'application' , 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
</body>
</html>

app/views/static_pages/index.html.erb
<% provide(:title, "Main") %>
<div class="center jumbotron">
  <h1>Welcome</h1>
  <h2>Sign Up to start your Edit App!</h2>

  <%= link_to "Sign up now!", new_user_registration_path , class: "btn btn-lg btn-warning" %>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.user_name) %>
<h1>Welcome <%= @user.user_name %></h1>
<h2>You have <%= pluralize(@characters.count, 'character') %> created</h2>
<p>You can create new, delete or edit old ones here: <%= link_to 'Your Characters', characters_path, role: 'button', class: 'btn btn-primary' %>